### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by Montandalar** [W3RQ01/advtrains_platform#1]
```
ModError: Failed to load and run script from /home/blockhead/.minetest/mods/advtrains_platform/init.lua:
/home/blockhead/.minetest/mods/advtrains_platform/init.lua:170: '}' expected (to close '{' at line 154) near '"australia:bluestone_brick"'
Check debug.txt for details.
```

**Comment by SamMatzko** [comment]
Hello Montandalar! I'm not sure why you're getting this error, I can confirm that my version of the mod works well. If you take a look at [line 170](https://github.com/W3RQ01/advtrains_platform/blob/master/init.lua#L170), you can see that the closing `}` does in fact exist, and is not on line 170, but on line 171.

The latest commit to [`init.lua`](https://github.com/W3RQ01/advtrains_platform/blob/master/init.lua) was from two weeks ago as of this writing, so I don't know how you could have gotten this error unless you edited the file yourself... is there something I'm missing?

**Comment by Montandalar** [comment]
To add more confusion to the mix, the current master is not the current version published on ContentDB.

**Comment by SamMatzko** [comment]
Yes, if you saw my previous now-deleted message I was obviously confused :D, sorry about that.

Apparently there are _two_ 2.1.1 releases, one of which is "2.1.1 Bwoken Mod Release" (you can see these two on [ContentDB](https://content.minetest.net/packages/W3RQ01/advtrains_platform/releases/). And as far as I can see, 2.1.1 (the more recent release on ContentDB) is associated with the commit _before_ "2.1.1 Bwoken Mod Release"

Maybe it would be simplest if we just submit a pull request, fix the error, and @W3RQ01 can create a new release?

**Comment by Montandalar** [comment]
Let me be clear about my points here: 

@SamMatzko in particular: GitHub issues are to be made, if not otherwise specified against the default branch of a repository unless otherwise specified. If something is wrong with master, I am going to make an issue. Master should never be in a broken state. It is presently, meaning anyone who pulls this repository is going to have a broken version of the mod by default. That's not good. However, the release tag 2.1.1 is in good working order. So the issue is from the repository side a development-version issue or on the end users' side - in some cases - an issue of people installing via git not knowing how to checkout a stable release (that's on them, using commits on master beyond a stable release is not guaranteed to work, you are effectively beta testing if you use them).

Secondly: Well-spotted that there is mismatch between ContentDB's "2.1.1" and the actual repository tag here. That release should be removed and replaced with the actual release. Git is authoritative.

Lastly: Master is past the tag 2.1.1, so of course any next release should be tagged appropriately in git and then published on ContentDB. Release management is up to the mod author/maintainer (in the absence of no published development methodology). While @W3RQ01 may create a new release, there is also no specific need for one right now, so long as a stable version is available on ContentDB and tagged appropriately in git. What there is definitely a specific need for is to rectify the situation on master.

**Comment by SamMatzko** [comment]
Good points! I agree.

**Comment by W3RQ01** [comment]
Error is resolved, I will create a release to fix it.
